### ISSUE TITLE
Oi! Ye got a loicense for dat?

### ISSUE THREAD

**Issue by lpaube** [iflis7/net_practice#1]
Salut. Comme ce repo est originalement le mien, il devrait contenir ma licence originale.

La licence stipule que tu peux faire ce que tu veux avec le repo: le copier, le modifier, le revendre, etc. **Tant qu'il contient toujours la licence originale.**

La licence peut etre trouvé ici:
[Laubester - NetPractice](https://github.com/Laubester/NetPractice)

**Comment by iflis7** [comment]
Added the credit and link to the licence.
A huge thanks for the reminder.
